

CREATE TABLE `archived_data` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATA` text NOT NULL,
  `FROMTABLE` text NOT NULL,
  `DATE` text NOT NULL,
  `COMMENTS` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=250 DEFAULT CHARSET=latin1;



CREATE TABLE `articles` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` text NOT NULL,
  `DESCRIPTION` text NOT NULL,
  `HTML_CONTENT` text NOT NULL,
  `COURSE` int(11) NOT NULL,
  `PAGES` text NOT NULL,
  `CREATED_DATE` text NOT NULL,
  `PUBLISHED_DATE` text NOT NULL,
  `PUBLISHED_USER` text NOT NULL,
  `PUBLISHED_STATUS` tinyint(4) NOT NULL,
  `CODE` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=latin1;



CREATE TABLE `courses` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` text NOT NULL,
  `DESCRIPTION` text NOT NULL,
  `PERMISSIONS` text NOT NULL,
  `ARTICLES` text NOT NULL,
  `HTML_CONTENT` text NOT NULL,
  `CODE` int(11) NOT NULL,
  `CREATED_DATE` text NOT NULL,
  `PUBLISHED_STATUS` int(11) NOT NULL,
  `PUBLISHED_DATE` text NOT NULL,
  `PUBLISHED_USER` text NOT NULL,
  `PAR_HOURS` int(11) NOT NULL,
  `OPEN_DAYS` int(11) NOT NULL,
  `MODIFIED_DATE` text NOT NULL,
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=latin1;



CREATE TABLE `groups_types` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CLOSED` tinyint(4) NOT NULL,
  `NAME` text NOT NULL,
  `DESCRIPTION` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;



CREATE TABLE `groupslist` (
  `ADMINUSERS` text NOT NULL,
  `NAME` text NOT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GROUPTYPE` text NOT NULL,
  `CLOSED` tinyint(4) NOT NULL,
  `AUTOJOIN` tinyint(4) NOT NULL,
  `DESCRIPTION` text NOT NULL,
  `REQUESTS` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;



CREATE TABLE `help` (
  `DATE` text NOT NULL,
  `HELPMSG` text NOT NULL,
  `USER` text NOT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



CREATE TABLE `member_view_history` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` int(11) NOT NULL,
  `HISTORY` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;



CREATE TABLE `members` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REGDATE` text NOT NULL,
  `PASSWORD` text NOT NULL,
  `NAME` text NOT NULL,
  `FULLNAME` text NOT NULL,
  `GENDER` tinyint(4) NOT NULL,
  `SURNAME` text NOT NULL,
  `EMAIL` text NOT NULL,
  `ROLE` text NOT NULL,
  `GROUPS` text NOT NULL,
  `CONTACTNUM` text NOT NULL,
  `FIRSTTIME` tinyint(1) NOT NULL,
  `SECURITYQUESTION` text NOT NULL,
  `SECURITYANSWER` text NOT NULL,
  `LASTLOGIN` text NOT NULL,
  `LASTVIEWED` text NOT NULL,
  `LOCKED` tinyint(4) NOT NULL,
  KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=latin1;



CREATE TABLE `messages` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FROMUSER` text NOT NULL,
  `TODATA` text NOT NULL,
  `SUBJECT` text NOT NULL,
  `MESSAGE` text NOT NULL,
  `TIMESTAMP` text NOT NULL,
  `STATUS` text NOT NULL,
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;



CREATE TABLE `modules` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SETTINGNAME` text NOT NULL,
  `DESCRIPTION` text NOT NULL,
  `NAME` text NOT NULL,
  `CODETORUN` text NOT NULL,
  `ACTIVE` int(11) NOT NULL DEFAULT '1',
  `PRIORITY` int(11) NOT NULL,
  `ONPAGE` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;



CREATE TABLE `pages` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` text NOT NULL,
  `HTML_CONTENT` text NOT NULL,
  `ARTICLE` int(11) NOT NULL,
  `CREATED_DATE` text NOT NULL,
  `PUBLISHED_DATE` text NOT NULL,
  `PUBLISHED_USER` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=latin1;



CREATE TABLE `role_permissions` (
  `PERMISSION` text NOT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` text NOT NULL,
  `NAME` text NOT NULL,
  `HIDDEN` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=latin1;



CREATE TABLE `roles` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLENAME` text NOT NULL,
  `DISPLAYNAME` text NOT NULL,
  `PERMISSIONS` text NOT NULL,
  `HIDDEN` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;



CREATE TABLE `securityquestions` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `QUESTION` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;



CREATE TABLE `statmessages` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MSGNAME` text NOT NULL,
  `MESSAGE` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;



CREATE TABLE `testresults` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TID` int(11) NOT NULL,
  `NAME` text NOT NULL,
  `XMLDATA` text NOT NULL,
  `STUDENT` text NOT NULL,
  `TESTDATE` text NOT NULL,
  `TIMETAKEN` int(11) NOT NULL,
  `RESULTS` text NOT NULL,
  `RATING` int(11) NOT NULL,
  `MARKED` tinyint(1) NOT NULL,
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;



CREATE TABLE `tests` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` text NOT NULL,
  `DESCRIPTION` text NOT NULL,
  `CODE` text NOT NULL,
  `ACCESS` text NOT NULL,
  `QUESTIONS` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `MISCCOMMANDS` text NOT NULL,
  `ALLOWEDTIME` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;



CREATE TABLE `tests_old` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` text NOT NULL,
  `DESCRIPTION` text NOT NULL,
  `CODE` text NOT NULL,
  `ACCESS` text NOT NULL,
  `XMLDATA` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TESTTEMPLATE` text NOT NULL,
  `MARKERTEMPLATE` text NOT NULL,
  `ANSWERTEMPLATE` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;



CREATE TABLE `tests_questions` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` text NOT NULL,
  `DESCRIPTION` text NOT NULL,
  `CLASS_FILE` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;



CREATE TABLE `testscontent` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTENT` text NOT NULL,
  `ACCESS` text NOT NULL,
  `ALLOWEDTIME` int(11) NOT NULL,
  `MISCCOMMANDS` text NOT NULL,
  `TESTNAME` text NOT NULL,
  `TEST` text NOT NULL,
  `DESCRIPTION` text NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;



CREATE TABLE `testscontent_old` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTENT` text NOT NULL,
  `ACCESS` text NOT NULL,
  `ALLOWEDTIME` int(11) NOT NULL,
  `MISCCOMMANDS` text NOT NULL,
  `TESTNAME` text NOT NULL,
  `TEST` text NOT NULL,
  `DESCRIPTION` text NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;



CREATE TABLE `testsmarks` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TID` int(11) NOT NULL,
  `DATA` text NOT NULL,
  `MARKEDON` text NOT NULL,
  `MARKEDBY` text NOT NULL,
  `SCORE` int(11) NOT NULL,
  `FINALCOMMENTS` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=latin1;



CREATE TABLE `tmp_email_validation` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` text NOT NULL,
  `CODE` text NOT NULL,
  `REQUEST_TIME` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



CREATE TABLE `tmp_test_questionlist` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` int(11) NOT NULL,
  `TID` int(11) NOT NULL,
  `QUESTION_LIST` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

